version: '3.7'

services:
  backend:
    image: samsun0196/spebackend3:latest
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - moviemate

  frontend:
    image: samsun0196/spefrontend1:latest
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - moviemate
    depends_on:
      - backend

  elasticsearch:
    image: elasticsearch:7.17.21
    volumes: 
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - moviemate
    depends_on:
      - frontend

  logstash:
    image: logstash:7.17.21
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
    ports:
      - "6000:6000/tcp"
      - "9600:9600"
    networks:
      - moviemate
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.17.21
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    networks:
      - moviemate
    depends_on:
      - elasticsearch

networks:
  moviemate:
    driver: bridge
