---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: false

  vars:
    compose_src: "docker-compose.yml"
    compose_dest: "docker-compose.yml"
    sleep_duration: 1200  # 16 minutes in seconds

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: "{{ compose_src }}"
        dest: "{{ compose_dest }}"

    - name: Ensure Docker Compose is installed
      command: "which docker-compose"
      register: docker_compose_location
      ignore_errors: yes

    - name: Install Docker Compose if not installed
      become: yes
      command: >
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      when: docker_compose_location.rc != 0


    - name: Run Docker Compose
      command: "docker-compose -f {{ compose_dest }} up"

    - name: Wait for the specified duration
      pause:
        seconds: "{{ sleep_duration }}"

    - name: Stop Docker Compose
      command: "docker-compose -f {{ compose_dest }} down"